# Generated by Django 2.1.5 on 2019-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(blank=True, default=None, max_length=75, null=True)),
                ('bathrooms', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('bedrooms', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('home_size', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('home_type', models.TextField(blank=True, default=None, null=True)),
                ('last_sold_date', models.DateField(blank=True, default=None, null=True)),
                ('last_sold_price', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('price', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('property_size', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('rent_price', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('rentzestimate_amount', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('rentzestimate_last_updated', models.DateField(blank=True, default=None, null=True)),
                ('tax_value', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('tax_year', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('year_built', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('zestimate_amount', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('zestimate_last_updated', models.DateField(blank=True, default=None, null=True)),
                ('zillow_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('city', models.TextField(blank=True, default=None, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, default=None, max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
    ]
